{
  service: 'user-service',
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  connectionGeneration: 0,
  level: 'error',
  message: 'Failed to conncet bad auth : authentication failed',
  stack: 'MongoServerError: bad auth : authentication failed\n' +
    '    at Connection.onMessage (E:\\Projects\\One.app\\One.app-Api-V2\\node_modules\\mongodb\\src\\cmap\\connection.ts:413:18)\n' +
    '    at MessageStream.<anonymous> (E:\\Projects\\One.app\\One.app-Api-V2\\node_modules\\mongodb\\src\\cmap\\connection.ts:243:56)\n' +
    '    at MessageStream.emit (node:events:519:28)\n' +
    '    at processIncomingData (E:\\Projects\\One.app\\One.app-Api-V2\\node_modules\\mongodb\\src\\cmap\\message_stream.ts:187:12)\n' +
    '    at MessageStream._write (E:\\Projects\\One.app\\One.app-Api-V2\\node_modules\\mongodb\\src\\cmap\\message_stream.ts:68:5)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:570:12)\n' +
    '    at _write (node:internal/streams/writable:499:10)\n' +
    '    at MessageStream.Writable.write (node:internal/streams/writable:508:10)\n' +
    '    at TLSSocket.ondata (node:internal/streams/readable:1007:22)\n' +
    '    at TLSSocket.emit (node:events:519:28)',
  label: 'HI',
  timestamp: '2024-10-17T23:57:24.967Z',
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
